module.exports={
    entry:'./Components/app.js',
    output:{
        filename:'./public/bundle.js'
    },
    module:{
        loaders:[
            {
                test:/\.js$/,
                loader:'babel',
                exclude:/node_modules/,
                query:{
                    presets:['react','es2015','stage-2']
                }
            }
        ]
    }
}